# Generated by Django 3.0.4 on 2020-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Book Name')),
                ('publisher', models.CharField(max_length=100, verbose_name='Published by')),
                ('isbn', models.CharField(max_length=25, unique=True, verbose_name='ISBN')),
                ('publish_date', models.DateField(verbose_name='Published on')),
            ],
        ),
    ]
